= About
{author}
:page-layout: base

== About me
My name is Paulo Jerônimo (aka PJ). I'm a Java developer, JBoss (http://www.redhat.com/en/services/certification/rhcja[RHCJA]) and Linux (http://www.redhat.com/en/services/certification/rhcsa[RHCSA]) administrator/ consultant. I'm also http://github.com/paulojeronimo/livro-jboss[working on a brazilian book about JBoss EAP]. I develop in programming languages and tools running under open or proprietary platforms, giving preference to produce open source software. Present in the corporate market since 1993, I work on solutions using JBoss stack and agile practices. I have extensive experience in architecture, development and infrastructure to meet the non-functional software requirements in mission critical, scalable, fault-tolerant, running on clusters of application servers in public or private computing clouds.

== About this site (how I did it)
As link:./index.html[I said], this website was made by using Awestruct and Asciidoctor. Here I present my work to use that tools to develop this site and publish his entire content on GitHub (source code and generated HTML pages). You can treat this topic as a plus tutorial, beyond which was the link:./tutorial.html[focus of my presentation] so ... let's begin ... (TODO)

// vim: set syntax=asciidoc:
